
CREATE TABLE quest_60_10000000 (
  ENCID TEXT NOT NULL,
  ENCU TEXT NOT NULL,
  ENCL TEXT NOT NULL,
  ENCCL TEXT NOT NULL,
  ENCD TEXT NOT NULL
);

CREATE TABLE quest_60_10000000_meta_opt1 (
  ENCD TEXT NOT NULL,
  ENCCOUNT TEXT NOT NULL
);

CREATE TABLE quest_60_10000000_meta_opt2 (
  ENCD TEXT NOT NULL,
  ENCL TEXT NOT NULL,
  ENCCOUNT TEXT NOT NULL
);
